# Generated by Django 2.2.3 on 2019-08-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190821_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
